### ISSUE TITLE
When React is not used, "null" is detected as library version

### ISSUE THREAD

**Issue by gregorybolkenstijn** [johnmichel/Library-Detector-for-Chrome#100]
Reproduce:
- Go to a website without React: https://www.google.com
- React still displays as used, but with version "null"

It's because of the check for the React devtools: https://github.com/johnmichel/Library-Detector-for-Chrome/blob/master/library/libraries.js#L383
Because I have that installed it's always showing "null"

**Comment by johnmichel** [comment]
@gregorybolkenstijn Please provide the exact URL where this is happening so that I can see which false positive is occurring.

**Comment by gregorybolkenstijn** [comment]
@johnmichel https://www.google.com :)

**Comment by gregorybolkenstijn** [comment]
Why is the check for __REACT_DEVTOOLS_GLOBAL_HOOK__ there? 
It will always give a false positive if you have the React DevTools installed it seems.

**Comment by johnmichel** [comment]
That check was added in #96.  I'll take a closer look at this to see if there is a way to maintain detection without blowing away the checks in there.

**Comment by johnmichel** [comment]
It also looks as though the React team has deprecated `createClass`, which was being used to validate the existence.  I'll also find a new replacement test for that moving forward.

**Comment by gregorybolkenstijn** [comment]
The test voor Greensock is also failing btw: Library Detector test for Greensock JS failed: ReferenceError: gs is not defined

**Comment by johnmichel** [comment]
@gregorybolkenstijn 
> The test voor Greensock is also failing btw: Library Detector test for Greensock JS failed: ReferenceError: gs is not defined

Which page is this occurring on?  I'm not seeing it when loading https://www.google.com

**Comment by gregorybolkenstijn** [comment]
@johnmichel The error for Greensock occurs on pages where Greensock is used: http://random.studio/

**Comment by johnmichel** [comment]
Resolved the `React` false positives with cd9b6d1a4ca1f07ef7dbac611da1b2e79e48095a and the `GreenSock` failures with cd9b6d1a4ca1f07ef7dbac611da1b2e79e48095a.
