### ISSUE TITLE
React detection issue

### ISSUE THREAD

**Issue by Solant** [johnmichel/Library-Detector-for-Chrome#105]
React with version null is detected on almost every page I visit.
![image](https://user-images.githubusercontent.com/5971578/32517945-24967a72-c419-11e7-8783-1b01002db1fc.png)

**Comment by johnmichel** [comment]
@Solant I'm unable to reproduce this with `4.3.0` in the latest stable version of Chrome.  Can you please provide details for your versions?

**Comment by Solant** [comment]
@johnmichel my bad. Looks like this issue was caused by Loom extension, this thing adds this
```
<div id="lo-engage-ext-container">
<div data-reactroot=""></div>
</div>
```
to body and `var altHasReact = document.querySelector('*[data-reactroot]');` test returns actual div instead of null.

**Comment by johnmichel** [comment]
Ahh, I see 😞

Unfortunately, I can't do much to work around that for now unless React radically changes how it exposes itself.
