### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier (libraries.js:729)

### ISSUE THREAD

**Issue by jh12z** [johnmichel/Library-Detector-for-Chrome#106]
An error is logged in Chrome Dev Tools coming from libraries.js line 729.
It seems there is a wrong character instead of a space between `||` and `UNKNOWN_VERSION` (hex:C2A0).
I'm using version v4.3.0.

```
return {version: win.RightJS.version ||Â UNKNOWN_VERSION};
```

**Comment by johnmichel** [comment]
Thanks for reporting this!  It should be fixed in `v4.3.1` now.
