### ISSUE TITLE
Extend to more than just JS libraries

### ISSUE THREAD

**Issue by housseindjirdeh** [johnmichel/Library-Detector-for-Chrome#132]
It can be useful to detect more than a specific JS library on a site (like a CMS tool for example). PRs have already been submitted to detect WordPress and Shopify (#127, #131) on a site.

We may want to change the naming/description of this tool to not just be a `js-library-detector`. Something like `technology-detector` might work.

**Comment by johnmichel** [comment]
I’m not sure that I would want to expand the scope of this library/extension too much more, but if enough people would want that, we could certainly investigate it, either as a fork or feature of this library.

**Comment by housseindjirdeh** [comment]
@johnmichel Sounds good, agreed that we always end up forking it in the future if need be 👍
