### ISSUE TITLE
Extension doen't work

### ISSUE THREAD

**Issue by agolikoff** [johnmichel/Library-Detector-for-Chrome#146]
It doesn't show icons:
![image](https://user-images.githubusercontent.com/16826887/67294402-71ca7c00-f4ee-11e9-875c-57807f0d2910.png)

**Comment by Huy-Ngo** [comment]
![image](https://user-images.githubusercontent.com/19296926/72204567-19cb6200-34ac-11ea-9438-778a94098941.png)

This issue still persist - here is what I see when I use it on Facebook. It doesn't detect React, which is a library used, or any other libraries. Please consider re-opening this issue.
