### ISSUE TITLE
Nuxt.js is not detected

### ISSUE THREAD

**Issue by koresar** [johnmichel/Library-Detector-for-Chrome#148]
Very weird.
Open this website: https://nuxtjs.org/
The Nuxt.js is not detected. Although the `window.$nuxt` exists.

**Comment by wellingguzman** [comment]
I noticed that too, it's not a bug, but the version on the chrome store is outdated (5.2.0), and the test for Nuxt.js was added in [v5.3.0](https://github.com/johnmichel/Library-Detector-for-Chrome/releases/tag/v5.3.0)

**Comment by johnmichel** [comment]
I've uploaded `5.6.0` to the Chrome Web Store that should include support for `Nuxt.js`.  It's currently under review for publishing.

**Comment by johnmichel** [comment]
This is now fixed in the published version that's available from the Chrome Web Store
