### ISSUE TITLE
Nuxt.js is still not detected in SSR mode

### ISSUE THREAD

**Issue by koresar** [johnmichel/Library-Detector-for-Chrome#157]
Hello.

I have a number of Nuxt.js websites. After #148 the Nuxt.js can now be detected if mode="spa". However, if mode="universal" (the default) then the extension can't detect Nuxt.

I triple checked. The `window.$nuxt` does exist in all my websites.

**Comment by johnmichel** [comment]
Can you please provide a link to a site where this is not functioning as intended?

**Comment by koresar** [comment]
flash-fx.com

**Comment by connorjclark** [comment]
@kyliau could you check if Nuxt detection is working as you'd expect? So we can make sure the new strings you added actually show up in Lighthouse
