### ISSUE TITLE
Velocity.js(1.1.0) version check cause an undefined error

### ISSUE THREAD

**Issue by ddaishin** [johnmichel/Library-Detector-for-Chrome#59]
Uncaught TypeError: Cannot read property 'major' of undefined
libraries.js line 865-867

I'm not sure, but I think it would be probably jq.Velocity.State.version.major moved to jq.Velocity.version.major

**Comment by xcskier56** [comment]
Any update on this one?

**Comment by pdenya** [comment]
+1 currently getting this issue with version 1.2.2

**Comment by johnmichel** [comment]
This appears to have been fixed and published under v2.7.3.
