### ISSUE TITLE
Leaflet detection not enough restrictive

### ISSUE THREAD

**Issue by Narno** [johnmichel/Library-Detector-for-Chrome#68]
For example on https://contacts.google.com/preview/all it detects the Leaflet library with an undefined version.
I think it's because the name is too short: "L".

I suggest we could force control of "version" property to be sure it's really the Leaflet lib:
```javascript
'Leaflet': {
        icon: 'leaflet',
        url: 'http://leafletjs.com',
        test: function(win) {
            if (win.L && win.L.version) {
                return {version: win.L.version};
            }
            return false;
        }
    },
```

**Comment by johnmichel** [comment]
@Narno, good catch!

This is something I've been meaning to go through as a part of #15.  Some of the library detection tests need to be hardened to handle situations like this.  It's been done for a handful of libraries, as seen [here](https://github.com/johnmichel/Library-Detector-for-Chrome/blob/3bb6dfb6ed0ee8b4cd1a3336186696480c84f73c/library/libraries.js#L1006), but more is definitely necessary.  This will be addressed soon.

**Comment by Narno** [comment]
@johnmichel, I can help with a PR of the code above if you want?
