### ISSUE TITLE
Detect KendoUI?

### ISSUE THREAD

**Issue by brownieboy** [johnmichel/Library-Detector-for-Chrome#72]
Can you add KendoUI to the list of libraries detected, please?

**Comment by brownieboy** [comment]
Actually, looking at the source code, I think I can add this myself.

I'll submit a pull request soon.

**Comment by robertpataki** [comment]
I made a pull request adding Kendo UI: https://github.com/johnmichel/Library-Detector-for-Chrome/pull/75

**Comment by johnmichel** [comment]
Closed with #75
