### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by 199911** [johnmichel/Library-Detector-for-Chrome#80]
I cannot find the icon in address bar.
I click the icon in extension menu, but nothing happen.

**Comment by johnmichel** [comment]
@199911 Can you include your version of Chrome and a screenshot of what seems to be going on?

**Comment by 199911** [comment]
@johnmichel 
It works how.
It does not show anything just because the plugin detect no libraries used.
Thanks for helping 😄

**Comment by johnmichel** [comment]
@199911 I'll have to update the screenshots to display how this extension works now since Chrome has shifted the display of extension icons.  Thanks for pointing this out.
