### ISSUE TITLE
Allow user to copy paste list of libraries and versions

### ISSUE THREAD

**Issue by jawn** [johnmichel/Library-Detector-for-Chrome#82]
Hello,

It's already great that you can see the list of libraries used. 
As far as I can tell, you need to take a screenshot if you want to capture the list of libraries and versions.

Suggestion: add "Copy extension list to clipboard" to the menu.

**Comment by robertpataki** [comment]
@jawn, you can select and copy the list of detected lib names and their versions already - isn't that enough?

**Comment by jimmont** [comment]
for those looking for a way to conveniently examine results, in the developer tools console filter/copy etc using the global devtools features like: `copy(d41d8cd98f00b204e9800998ecf8427e_LibraryDetectorTests)` (this doesn't address the feature requested, simply relates)

**Comment by jawn** [comment]
Closing the issue since the original question is no longer important to me, after 4 years.
