### ISSUE TITLE
doesnt display

### ISSUE THREAD

**Issue by XtremePlayzCODE** [johnmichel/Library-Detector-for-Chrome#84]
the only thing i see is a blank icon in the extensions bar

EDIT: Some of my sites that have jQuery don't display in the extensions bar when there is in fact jQuery on my site

**Comment by Narno** [comment]
This is the case if there is no librairies detected.

Try with https://www.openstreetmap.org, it should detect Bootstrap, jQuery and Leaflet.

**Comment by johnmichel** [comment]
@XtremePlayzCODE Do you have links available for the aforementioned sites?  I could take a look and see what might be causing the extension to not display the correct icons.

**Comment by XtremePlayzCODE** [comment]
Nevermind, now the Library Detector icon is displaying instead of just a blank square. And everything is detected.

**Comment by johnmichel** [comment]
That is the result of changes made to resolve #83.  Glad everything is in working order again.

**Comment by XtremePlayzCODE** [comment]
Yup, me too

**Comment by XtremePlayzCODE** [comment]
Whoops, wrong button
