### ISSUE TITLE
Angular 2 doesn't seem to be detected

### ISSUE THREAD

**Issue by joaocc** [johnmichel/Library-Detector-for-Chrome#88]
I am trying to find examples of sites where angular 2 is detected, but so far no luck.
Some example sites:
* http://azimuth.themeseason.com/pages/dashboard
* https://genesisui.com/demo/genius/bootstrap4-angular2/#/dashboard
* https://core.mediapixeldesign.com/examples/dashboard
* http://primer.nyasha.me/home

All these are supposed to be angular 2.x, but Library detector doesn't show anything in that sense.
Thanks

**Comment by johnmichel** [comment]
Angular 2 support has not been added yet.  If you'd like to add support for it, please feel free to open a PR, otherwise, I can look into it later this month.

**Comment by rviscomi** [comment]
Fixed by https://github.com/johnmichel/Library-Detector-for-Chrome/pull/90
