### ISSUE TITLE
Add a few new libraries and increase coverage for others

### ISSUE THREAD

**Issue by tlauinger** [johnmichel/Library-Detector-for-Chrome#89]
I'd like to contribute some new/improved tests for libraries that we created a while ago when using Library Detector's code for a project:

- _New libraries:_ swfobject, flexslider, moment-timezone (plug-in for Moment.js), json3, pep, spf, numeral

- _Updated tests:_ Leaflet, Socket.IO, RequireJS, Pixi.js, Moment.js

If you're interested in integrating these tests, should I open a single PR for all of them, or an invididual PR for each library?

**Comment by johnmichel** [comment]
Thanks; this sounds great!

I'd prefer a single PR, but you can do individual commits within the PR for each library to keep things compartmentalized.

**Comment by tlauinger** [comment]
A short note about #91: I ended up not including JSON3 and PEP in the PR because the tests we have are quite fragile and cover only very few versions of these two libraries, so they aren't that useful after all.

(It looks like we can detect only a single PEP version, and only if used together with jQuery. JSON3 replaces the built-in JSON object and leaves few or no other traces behind, so it's complicated to detect and the test we came up with might also incorrectly match non-library objects.)
