### ISSUE TITLE
Ship libraries.js on npm?

### ISSUE THREAD

**Issue by paulirish** [johnmichel/Library-Detector-for-Chrome#98]
There's now two cases where it'd be very useful to have the libraries js file shipped as an npm module

1. https://github.com/GoogleChrome/lighthouse/pull/2372/files/9ebc72b0594d94d7e34e51c920e99715d7befd2c..26af2459d6a0b33f5ec3621cd7bf9fa54c69d9b9#r118730159
1. https://github.com/HTTPArchive/httparchive/commit/5a624cbcf0b7528acc48a67a582e5a95dacf7b04#diff-4df11ed88be41bcc1851345666d6f7b1

Do you think it'd be possible to do this?

**Comment by johnmichel** [comment]
This is certainly something that could be done; I'd be happy to help out.  I can get that done in the next couple of days as I'm away for the long weekend.

**Comment by johnmichel** [comment]
@paulirish I've published it at [`js-library-detector`](https://npm.im/js-library-detector)!

Please let me know if there are further updates that need to be done to `libraries.js` to make it more useful for `lighthouse` and `httparchive`.
