### ISSUE TITLE
False detection on some web pages

### ISSUE THREAD

**Issue by Solant** [johnmichel/Library-Detector-for-Chrome#99]
False detection happens on pages like https://vuejs.org/v2/guide/comparison.html where, for example `window.Polymer` is actually `HTMLElement`. Maybe add `obj instanceof HTMLElement` check before running test functions?

**Comment by johnmichel** [comment]
Thanks for pointing this out.  The false positive for Polymer here is due to less specific checks on some libraries.  I'll spend some time this week hardening detection for those libraries.

**Comment by johnmichel** [comment]
This was resolved with 5699fad2b770f54889bbd4eaa1b6e1a3b9c538c4.

**Comment by Solant** [comment]
@johnmichel thanks, have a nice day.
